controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_finger_left_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: start